apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: lcow-injector-cfg
  labels:
    app: lcow-injector
webhooks:
  - name: lcow-injector.sachinmsft.me
    clientConfig:
      service:
        name: lcow-injector-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods","deployments","replicasets","statefulsets"]
